# sudo: required
language: node_js
node_js:
    - "10"
    - "9"

services: 
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
        - IMAGE=an19940611/webpackbuild
#         - IMAGE_VERSION=$IMAGE:$COMMIT
#         - DEPLOYMENT=frontend
#         - CONTAINER_NAME=nodejs

before_script:
    - docker build -t $IMAGE . --no-cache
    # docker tag 標記本地鏡像，將其歸入某一倉庫 # https://blog.csdn.net/yangshangwei/article/details/52799675
    # 避免抓不到預設 手動上latest
    - docker tag $IMAGE $IMAGE:latest

script: 
    # start mocha test
    - npm test
    # pass test and start compiler Image
    # - docker build --rm -t $DEPLOY_ACCOUNT/$DEPLOY_IMAGE .
    # -t: terminal, 讓操作者可以使用終端機操作intance
    - npm dockerServer; sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:3000

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      # 1. 推到docker hub  # process: https://docs.travis-ci.com/user/docker/
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      # push會抓預設latest #其他指令如 docker rmi 若沒指定tag 也會自動抓取latest
      docker push $IMAGE;

      # 2. 推images 到heroku
      #   // do the deploy https://stackoverflow.com/questions/31338562/travisci-run-after-success-on-a-specific-branch
    #   heroku container:login
    #   heroku container:push web
    # After you’ve successfully pushed an image to Container Registry, you can create a new release using: heroku container:release web
    #   heroku container:release web
      fi
    
    # - docker build -t "$DOCKER_USERNAME/webpackbuild"

# deploy:
#     provider: heroku
#     api_key: 
#         secure: travis encrypt $(heroku auth:token) --add deploy.api_key --pro
#     app: webpackBuild

    # Docker 部署，只要在儲存庫內放上 Dockerfile，透過 Heroku CLI 指令就可以將 Docker 容器上傳到 Heroku Docker Registry
    # https://devcenter.heroku.com/articles/container-registry-and-runtime

    # heroku container:login
    # git clone https://github.com/heroku/alpinehelloworld.git
    # heroku create
    # heroku container:push web
    # heroku container:release web
    # heroku open
    # travis test docker!!!!!

# process => (code + dockerfile + tests) => source repo => Travis CI server (1.run tests && build service 2. docker build package 3. docker rigistry(登陸檔)) ＝> docker push (deploy)
# docker process # https://columns.chicken-house.net/2017/08/05/what-cicd-do-you-need/
# Docker + Travis CI + Kubernetes + GKE # https://ithelp.ithome.com.tw/articles/10196743
# 用 Travis 自動上傳 Docker Image 到 Docker Registry # https://blog.wu-boy.com/2016/09/upload-docker-image-to-registry-using-travis/
# travis doc(with docker) Using Docker in Builds # https://docs.travis-ci.com/user/docker/


# https://chengl.com/docker-workflow/

# env: #　step1 設定docker環境變數
#     global:
#       - secure: AoSvVfpX77AtMBpXKyHH67wTKWCN9xdXoMWroU2TwewBRToebQmLUesT+6gP2rCVoQ282IpESkZkIUumj38rvCGWpL3fLU67Fb1Fa/SqKQ++OYri3NNmoOLltkHMCHHz2bl7B8/72KJQ8e+sl8KCmKBTaLp1g2/36+DZwL9KZjFOqsQg2pwv3zjOUkZte6v6Igsl7lV1pbLkg9Fq1KEvOZl8D6bHgtNuHJGYZZrHCUDHMXxXeQ8/wL0v7GpUkZAe85Ve+fkPoX7AXYumbi5SsxbwVYG64j4zdU2ydlhmMRfOrT4BIbOHUO1kmP5uSf4/xX+fGJZuGDlVT1P5RTZyvu1dA+X10a0t2pOYHAjTjJp6CNRIKuJ4izBvxCZaLAUd42FfU9BAFyUPlViaDzNZAW3DCoapfnS0xM+UY1U8Z7bs+lIXycqIE6OR4KZXfKtpoKakmh8d0eY8LpUNu81VS9Z2mxfRg0xsYhp/1E/X+LZM/YCzPpOhQCc0ZGJEtbqj1/Qebp/GRBIx9oabBH+JxldqrZApIF0MsGiaIT8Q0LJ8wNVVc7QQqhjwdtvP1Wh2pxOvnzEyAdB4AeKrYv0SMwa3OxpIDtJEP1AvXRTZWXPObSSgAhK2VPnOK9Y++N2BlSKJh9k1nlnzn0FQsHlPUV/r9Ui62tmQbzOyL69xltQ=
#       - secure: KLweub+lnStvWmKY/XoDy8nXo4v5lYTHapXtewfDFrnWPL6UQV//kklUAswzGEWp4id9pOolZB4RNfucCBzB1Kb1KgSp23wz9mj+HWY+qUQRsLyIxYwsZf/o9H/MMkesG8jOF/vU35Ne3e7MdSmpNuqEqErIqc25691rBMLSDxi5YS3jcB+vGkv38xtlcDilnUrSneKuNEzuI5Q7MKr6vqIVaW3vbwEs5hEh2oPSAgVno67s9NyfUi2Dl4sIDDwzV+iXc9FNk4Ww6Vkm8uzZvIXhZDuyVnFWSJhgfNgElUna7XfqnWOyPdZQ0rh2iOtKzO9uZQiOoNq8JuT9VstFcFlhsfAtlynB5Xgp/EH9NUIZvUiueRhs0bOH9SKRUijIeTQ/OimuX0y8EZdz7TKSigZkc7iVqD0g2E2kLtv3avTCodwts54V8bX7//r8Y2FE7DFkZRGL7Khf5LPjRj7xVEb9OhEkuSYfs0oEhqyXCSMUNyov3BDFbZ/AWh0smQmKYv36U2JvMfPghNlgAE+b/Xc4F/sJMmNSDdLBmGwoJDJtVA5iB3RCfkZfEeqhMoj2C8uu8s8IASzxh2HnaaO5IQKy7kGwAzzRfazTq6JhvLPfteOKStvRYrLLBll7l2DPazLJK8ctKZ6CTFxoycU+R73IliwwpqLCAhasD9N7Q8w=
#       - secure: htu5A6fjnQvJTvinumWI1u1unoDMgY5FleGM8JwVLBQl6Srr1GU/2ulii1LSbypG/JimwMzT6BIRMfNgCzAeBc6aWM8xbZUsLl7p+WFyYNxOW26mVm8Z5R+2JZXm3vZoevjHD35gWIBMReqVySIRLXanZ9SOVRC1IcX2Om1uOoQHAqwrFh4KERWnzepAXylfUtFatqmRmCRczH4m9MKF7OgbZD/7xKHHoJxXLHjmWaCQrLmucb01/e/vl3C/LwOvc+A6fwXhhMFdL5UUn9iVWLBhTYknULjOKDF2AgvahvStxGUEAcscaW4qATW32Ylamn3K4l5X+3ic+fLKQHOR+oCaVmaqcpExbxuBfLHGQkV7DiUePQsS1D5NLfAHBdbd8MJCwxQRlSIt/z/aemkx6uWEBu053c47yuuKltFhAm6B7Z52UkHC8fpFfuy03xgorjNTayghPlYDeFZRzItkibTEY1EH4Sh9yVkAIhv5hqomMQMAkxaEFgmBkK7/8+UHB+sMlBupMiejTqIgZOzIhj1uqDGkokqI2UqlNx1wuqzGJ/KnQWzsgFsnoU0Q1zIzw0i1RAiDu8qj5vSnioqw8pvZWuBDuRltE5U4fup529ZtFSNx4Ceb3ECathc6+3Em8OvtqvBOr44xNBW8XCFbi82Ys3Dd/SEHGwlcwYoT4/A=
#       - secure: W1CzoMk6zUyhKhx+Q4mX/O1rh7GKFTrMNpkJ+QqN4WN56K3v49t6kotABXbFU4K8ZP84DhUkQYtm6DbEgCkxeNaT0k0gzKyG+CZo5sI6yqx15CwmR/qCkFruDQqUG/2hZNTP5ZP/7hMQwNCxATxuzu2GOcnwk1YuIJsJ5by9+RdWwKBYYhSG/BokNq6JaYxZx8NeMTa5W/CJXtu/5qFsMDQ07Syg4MgAnRHbRB9uCxpUOtJ44HDhZFOOY48qIDVpYhVpTg0XVzw5VkFNgOuczIYWw/SaWyOyoKgt8FtLhUPDsHtvueFqSJffYlyoh81Uxu+LNAtZoact5wFOwkDM+mzqRe/lzm2hcYY0nc4Dxc1ito43GedQmFnadZSozZfKAEmRV0m+1W6iE6fi+DpHXm3JCmgvolB9khLiYVTHkgaSzbfZDfdBmoXPEcaDuKnY6KTB410sGnadO6IT3Z5x8FtMQ/In/dB7XQr/G1aXve3KjUz8/oLZbS+IWEH8eQEOAR8V6w6HpvQIZE6ccwEzmLILlygne7TSAnOPQX1hiEDdUYYOtoyVEv/NUzd/OpGqNl6edYsXZB1bcY7FWy2YhmJD4mqe5h6mp4yRXYyuFbdC3OIBGpr1vnNaF9uUdayZ59pZ4kIojCQL2SKZKqOYdezyV/h0ohP93FIboi/nL7Q=
#       - secure: jxY+/q6svho30zk1RMtnwHhHkYMw+NqQS4n7dOILpsI6zKwC4n2c+xjD0MoOYjVsd/SiJucXeeNR4BcS4+OglsVxja68rBWqV4F3xloGwtMZebqMhNGSV4kitgAkdDNktQid2fQAwUsoCtEfq3A6ijMdOgoehZwxXqFg5+5cRwjI58vVOfdFDGPUO6KXTDhwwXIgTi9zN8nXSNCgHUZfrIGw6jTdFvL2NGkejbX4AqutethTlXlA7lVeE/O1SUW4H8MRl59MyKUwWm/j7qkmM/TX+PUaXSwXgoR0Nzbt2DKTbY56qff1olHaUMuV5c8A5gYlThvVYbMnGRTK7JYOzmchyvRsqc1inxIwU7bi/J1DnQpCX4qF06NBU+OLbx8+qDc9E6l9XGdQ09HFVPOctlNrkfcPDgGVfRYwomU8+gb8MykgBxtUqLIpJN0pr9sNZN4L4jGuv58ThkCfoaH6YgiLKTITJ7cLAE2tNmHj5Kw+vHNvJcUltRdMOSaDI6TyAGkVpUSHaTEOvdvsj5y5wFS3TdIHnTQOWMpBiYSHY7D4trvv6KRagDjoB7DKaAohYPwataJdu3Wu+A0UIsukYPG6uVn4RPJmQHBMT8vTtf9q9eSpoRU68zSnhAL5aXtq1vqtfy4859QQDzpH7JMA87WtJqCQ4Fp8MHOg3uvb+ZM=
#       - secure: FXEj1gwSi+xjpc4GFFS4ehxy6Q4wpmmPq/rlfWijOAYsNwukfkL2gCmnzjTT6ZZVHM47bNtHlTdqTM8bmBjWVeVEPKwvULq6i2neiGI7OI0vh2dsbCMIZ7bCMuRL0/WRq/A8YPsXIK76YIlMg8sSzdGdAmvZpjTbLywSl9KoSlH3S56e2Nz1kb8DhP4emeFcxdXul463JUdOBpCZa8oJLopOaX5+PypOk6XOjOyWkxN938F4w5/4MzhgghcrTRwtOQCPHyJR2zg08MWm5COKi3L2EmgPyctXGGr31YVeRTC9Gg3SJ+Mt8OfsX8f7TnUzhnfA3IszJpxw4cF1snpVmXZED2J1Aa6Gi7mSIhb1CdYNUxUKx6BVnaUGDRfmcxtGOt8Uy0A2sRl3FGhVVH6xQaaTmG3nzU0fm44cO1RwxqXfP4kXqUNj+LlCUC+3hIRrWRMfxjIWwGA0LZIqnVlou2TRLkxdM3IHx46cFqEfpD6Do/NXOCUZYRcE95FqvK6ZrobsZapkI0WkmoO4YdzCkuW9nSc8Y121OWlP9urkzaU4X7tO7FbLshKmjYNL4vLqyJ0gkN21yVJTIJWE6l/TGGi+RxwFF2jzN8oRjOJrWESmUSPa5WhNvuIOu1t0RObwRup0yjArRuUIXxuQt99c1tkfsn52fZWZih3t4bM0bxE=
#       - CLOUDSDK_CORE_DISABLE_PROMPTS=1
#       - COMMIT=${TRAVIS_COMMIT::8}
#       - IMAGE=chenglong/simple-node
#       - IMAGE_VERSION=$IMAGE:$COMMIT
#       - DEPLOYMENT=frontend
#       - CONTAINER_NAME=nodejs
  
# before_script: # step2 build docker image
    # - docker build -t $IMAGE:$COMMIT app
    # - docker tag $IMAGE:$COMMIT $IMAGE:latest
    # - docker tag $IMAGE:$COMMIT $IMAGE:travis-$TRAVIS_BUILD_NUMBER

# script: # step3 跑測試
#     - docker version
#     - docker-compose version
#     - docker-compose -f docker-compose.ci.yml run test

# after_failure: # step4 測試失敗
#     - docker stop $(docker ps -a -q) #stop docker
#     - docker rmi $(docker images -a -q) #delete images

#sample
# after_success: # step4 測試成功上傳server // gcp || ec2 (can support docker is ok) && buy one domain
#     - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#     - docker push $IMAGE # 將映像檔推上
#     - curl https://sdk.cloud.google.com | bash # 安裝最新的Google Cloud SDK，因為Travis上的版本太舊
#     - source /home/travis/.bashrc
#     - gcloud components update kubectl
#     - kubectl config set-credentials default --username=${GKE_USERNAME} --password=${GKE_PASSWORD}
#     - kubectl config set-cluster default --server=${GKE_SERVER} --insecure-skip-tls-verify=true
#     - kubectl config set-context default --cluster=default --user=default
#     - kubectl config use-context default
#     - kubectl patch deployment $DEPLOYMENT -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$CONTAINER_NAME"'","image":"'"$IMAGE_VERSION"'"}]}}}}'
